global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'postgres'
    static_configs:
      - targets:
          - 'postgres-exporter-node1:9187'
          - 'postgres-exporter-node2:9187'
          - 'postgres-exporter-node3:9187'
        labels:
          cluster: 'cluster-db-tp'