#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
CREATE ROLE replicacion WITH REPLICATION LOGIN PASSWORD '${REPL_PASSWORD}';
CREATE USER monitorizacion WITH PASSWORD '${MONITOR_PASSWORD}';
GRANT pg_monitor TO monitorizacion;
CREATE USER aplicacion WITH PASSWORD '${NODE_PASSWORD}';
GRANT CONNECT ON DATABASE clusterdb TO aplicacion;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO aplicacion;
ALTER DEFAULT PRIVILEGES FOR ROLE administrador IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO aplicacion;
EOSQL
